name: Main

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    APP_MODE: "ci"
    AUTH_MODE: "none"

jobs:
    backend-ci:
        uses: DCC-BS/ci-workflows/.github/workflows/ci.yml@b0f3abf4e131b4834279fb3ba3b4ecf366c52fdc #v10
