name: Main

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    APP_MODE: "ci"
    AUTH_MODE: "none"

jobs:
    backend-ci:
        uses: DCC-BS/ci-workflows/.github/workflows/ci.yml@5c025e5e2adac20a8b873e429b7112954326132a #v10
