name: Main

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    APP_MODE: "ci"
    AUTH_MODE: "none"

jobs:
    backend-ci:
        uses: DCC-BS/ci-workflows/.github/workflows/ci.yml@a46e69bb86a790352d822ab122e187c13597593a #v10
        with:
            run-build: false
